<?php

return [
    // Optional legacy Excel template path (no longer required when template_columns is set).
    'template_path' => storage_path('app/templates/baselinker_master.xlsx'),

    // Canonical list of output template columns (strict order, names match our master sheet).
    'template_columns' => [
        'Supplier',
        'Brend  ',
        'Product name (EN)',
        'Product name (PL)',
        'Order No.',
        'Sku',
        'our Sku ',
        'Supplier Product ID',
        'EAN / Barcode',
        'Item',
        'Qty (Quantity per Unit)',
        'item_category',
        'item SubCategory',
        'Написаанно на этикетке товара ',
        'Номер в EXL',
        'Season/Collection',
        'Collection',
        'Gender',
        'Product Line',
        'Color Code',
        'Color Description EN',
        'Color Description PL',
        'Общая колонка размеров',
        'Size Xs-Xl',
        'Age Size ',
        'Height Size',
        'Socks Size',
        'Hats Size',
        'Shoe size',
        'Wholesale Price EUR',
        'Recommended Retail Price EUR',
        'Wholesale Price PLN ',
        'Recommended Retail Price PLN',
        'Basis Unit',
        'Basis Unit Quantity',
        'Diameter ',
        'Weight KG',
        'Height CM',
        'Width CM',
        'Length CM',
        'Description EN',
        'Description PL',
        'Images 1',
        'Images 2',
        'Images 3',
        'Images 5',
        'Images 6',
        'Images 7',
        'Images 8',
        'Images 9',
        'Images 10',
        'Warehouse',
    ],
    'jobs_dir' => storage_path('app/imports'),
    'mapping_overrides_dir' => storage_path('app/import_mappings'),
    'normalization_rules_dir' => storage_path('app/normalization_rules'),
    'supplier_profiles_dir' => storage_path('app/supplier_profiles'),
    'normalization_safe_columns' => [
        'Gender',
        'Season',
        'Color Description EN',
        'Color Description PL',
        'Age Size',
    ],
    'export' => [
        'xlsx_name' => 'output.xlsx',
        'csv_name' => 'output.csv',
        'preview_json' => 'preview.json',
        'errors_json' => 'errors.json',
    ],
    'validation' => [
        'required_columns' => [
            'sku' => 'Sku',
            'name' => 'Product name (EN)',
            'price' => 'Wholesale Price EUR',
        ],
        'empty_row_threshold' => 0,
    ],
];

